name: radiko-on-spotify

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stations:
          - { station: TBS,     playlist_id: 11OVi6X97j56J64adgdF5o }
          - { station: QRR,     playlist_id: 304jv8dR1DnFveTH969ObD }
          - { station: RN2,     playlist_id: 0MZ068JyJDhdOGDoAc1LML }
          - { station: INT,     playlist_id: 6ql2qiuO69kjTZK8FZzDyJ }
          - { station: FMT,     playlist_id: 0hzw8H4PSmFDd0K952AjT7 }
          - { station: FMJ,     playlist_id: 2dK6F6vzYm9yfPI7MCkAb7 }
          - { station: BAYFM78, playlist_id: 0AzldR8iNos8ZpUDc6uQUu }
          - { station: NACK5,   playlist_id: 4bznTT4izxtHxWJNnEo6lL }
          - { station: YFM,     playlist_id: 0YEpGbfFBxo04HGIQzldMM }
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          architecture: x64
      - run: pip install requests pandas
      - run: python3 ./main.py $REFRESH_TOKEN $CLIENT_TOKEN $CLIENT_SECRET $STATION $PLAYLIST_ID
        env:
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          CLIENT_TOKEN:  ${{ secrets.CLIENT_TOKEN }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          STATION:       ${{ matrix.stations.station }}
          PLAYLIST_ID:   ${{ matrix.stations.playlist_id }}
      # - name: Commit new musics
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: Add latest musics by gh-actions
