name: radiko-on-spotify

on:
    schedule:
        - cron: '*/20 * * * *'
    workflow_dispatch:

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                python-version: 3.x
                architecture: x64
            - run: pip install requests numpy
            - run: python3 ./main.py $REFRESH_TOKEN $CLIENT_TOKEN $CLIENT_SECRET
              env:
                REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
                CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}
                CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
